# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The job that will use the container image you just pushed to ghcr.io
  super-job:
      runs-on: ubuntu-18.04
      container:
          image: ghcr.io/spinw/compiler:v1
          credentials:
             username: wardsimon
             password: ${{  secrets.CONTAINER_TOKEN }}
          options: >-
            --mac-address ${{  secrets.MAC_ADDR }}
      steps:
          - name: Set permissions
            run: |
              sudo chmod -R 777 /__w
          - name: Check out this Repo
            uses: actions/checkout@v2
          - name: Generate Licence
            shell: bash
            run: |
               ls ./
               sudo mkdir /opt/matlab/R2022a/licenses/
               sudo chmod -R 777 /opt/matlab/R2022a/licenses/
               gpg -d --batch --passphrase ${{  secrets.LIC_KEY }} ./license.lic.gpg > /opt/matlab/R2022a/licenses/license.lic
          - name: Checkout tools repo
            uses: actions/checkout@v3
            with:
              repository: wardsimon/cautious-happiness
              path: my-tools
          - name: Checkout SpinW repo
            uses: actions/checkout@v3
            with:
              repository: SpinW/spinw
              path: spinw_scr
          - name: Move components
            shell: bash
            run: |
              mkdir scr
              cp ./my-tools/* ./scr
              mkdir scr/CTF
              mkdir scr/CTF/SpinW
              cp -R spinw_scr/swfiles scr/CTF/SpinW
              cp -R spinw_scr/dat_files scr/CTF/SpinW
              cp -R spinw_scr/external scr/CTF/SpinW
          - name: Build
            shell: bash
            run: |
              /opt/matlab/R2022a/bin/mcc  -W python:pySpinW -d "./pySpinW" -v
                -a "scr/CTF"
                "scr/call.m"
                "scr/call_method.m"
                "scr/thinwrapper.m"
                "scr/wrap_obj.m"
                "scr/has_thin_members.m"
                "scr/recfind.m"
                "scr/getArgOut.m"
                "scr/get_method_refs.m"
                "scr/get_global.m"
                "scr/set_global.m"
                "scr/waitforgui.m"
                "scr/pythonFunctionWrapper.m"
                "scr/call_python_m.m"
                "scr/pyclasswrapper.m"
                "scr/check_wrapped_function.m"
                # "$<TARGET_FILE_DIR:call_python>/call_python.${Matlab_MEX_EXTENSION}"
                # "$<TARGET_FILE_DIR:pythonRemoveFuncKey>/pythonRemoveFuncKey.${Matlab_MEX_EXTENSION}"
            #   /opt/matlab/R2022a/bin/matlab -nodisplay -nosplash - nodesktop -r "ver; exit"

