# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The job that will use the container image you just pushed to ghcr.io
  super-job:
      runs-on: ubuntu-18.04
      container:
          image: ghcr.io/spinw/compiler:v1
          credentials:
             username: wardsimon
             password: ${{  secrets.CONTAINER_TOKEN }}
          options: >-
            --mac-address 02:42:ac:11:00:02
            
          
      steps:
          - name: super-step
            shell: bash
            run: |
              # Whatever commands you want to run here using the container with your
              # new Docker image at ghcr.io!>
              echo "--This is running in my custom Docker image--"
              ifconfig
              matlab -V
