# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The job that will use the container image you just pushed to ghcr.io
  super-job:
      runs-on: ubuntu-18.04
      container:
          image: ghcr.io/spinw/compiler:v1
          credentials:
             username: wardsimon
             password: ${{  secrets.CONTAINER_TOKEN }}
          options: >-
            --mac-address 02:42:ac:11:00:02
      steps:
          - name: Set permissions
            run: |
              sudo chmod -R 777 /__w
          - name: Check out Repo
            uses: actions/checkout@v2
          - name: Generate_Licence
            shell: bash
            run: |
               ls ./
               sudo mkdir /opt/matlab/R2022a/licenses/
               sudo chmod -R 777 /opt/matlab/R2022a/licenses/
               gpg -d --batch --passphrase ${{  secrets.LIC_KEY }} ./license.lic.gpg > /opt/matlab/R2022a/licenses/license.lic
          - name: Checkout tools repo
            uses: actions/checkout@v3
            with:
              repository: wardsimon/cautious-happiness
              path: my-tools
          - name: Checkout SpinW repo
            uses: actions/checkout@v3
            with:
              repository: SpinW/spinw
              path: spinw_repo
          - name: test-run
            shell: bash
            run: |
              /opt/matlab/R2022a/bin/matlab -nodisplay -nosplash - nodesktop -r "print(ver); exit"

